ifrikiya_user:
    resource: "@ifrikiyaUserBundle/Resources/config/routing.yml"
    prefix:   /
ifrikiya_auteurs:
    resource: "@ifrikiyaAuteursBundle/Resources/config/routing.yml"
    prefix:   /ifrikiya/auteur
ifrikiya_site:
    resource: "@ifrikiyaSiteBundle/Resources/config/routing.yml"
    prefix:   /
ifrikiya_admin:
    resource: "@ifrikiyaAdminBundle/Resources/config/routing.yml"
    prefix:   /ifrikiya/admin
ifrikiya_abonnees:
    resource: "@ifrikiyaAbonneesBundle/Resources/config/routing.yml"
    prefix:   /ifrikiya/abonnee
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile 
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register 
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile