security:
    encoders:
        ifrikiya\UserBundle\Entity\User:
          algorithm: sha512
          encode-as-base64: true
          iterations: 10
         
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_AUTEUR, ROLE_MODERATEUR,ROLE_USER]      
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH] 


    providers:
        class:
            id: fos_user.user_provider.username
    firewalls:
        main:
            pattern:        ^/
            anonymous:      true
            provider:       class
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:       fos_user_security_logout
                target:     /
            remember_me:
                key:        %secret% # %secret% est un paramètre de parameters.yml
        auteur:
            pattern:        ^/auteur
            anonymous:      true
            provider:       class
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:       fos_user_security_logout
                target:     /
            remember_me:
                key:        %secret% # %secret% est un paramètre de parameters.yml
    access_control:
        - { path: ^/ifrikiya/admin, roles: ROLE_ADMIN }
        - { path: ^/ifrikiya/auteur, roles: ROLE_AUTEUR }