<?php

namespace Proxies\__CG__\ifrikiya\SiteBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Livres extends \ifrikiya\SiteBundle\Entity\Livres implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getIdlivre()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idlivre"];
        }
        $this->__load();
        return parent::getIdlivre();
    }

    public function setTitre($titre)
    {
        $this->__load();
        return parent::setTitre($titre);
    }

    public function getTitre()
    {
        $this->__load();
        return parent::getTitre();
    }

    public function setAnnee($annee)
    {
        $this->__load();
        return parent::setAnnee($annee);
    }

    public function getAnnee()
    {
        $this->__load();
        return parent::getAnnee();
    }

    public function setPresentation($presentation)
    {
        $this->__load();
        return parent::setPresentation($presentation);
    }

    public function getPresentation()
    {
        $this->__load();
        return parent::getPresentation();
    }

    public function setPrixUnitaireFcfa($prixUnitaireFcfa)
    {
        $this->__load();
        return parent::setPrixUnitaireFcfa($prixUnitaireFcfa);
    }

    public function getPrixUnitaireFcfa()
    {
        $this->__load();
        return parent::getPrixUnitaireFcfa();
    }

    public function setFormat($format)
    {
        $this->__load();
        return parent::setFormat($format);
    }

    public function getFormat()
    {
        $this->__load();
        return parent::getFormat();
    }

    public function setPrixUnitaireEuro($prixUnitaireEuro)
    {
        $this->__load();
        return parent::setPrixUnitaireEuro($prixUnitaireEuro);
    }

    public function getPrixUnitaireEuro()
    {
        $this->__load();
        return parent::getPrixUnitaireEuro();
    }

    public function addIdEcrivain(\ifrikiya\SiteBundle\Entity\Ecrivains $idEcrivain)
    {
        $this->__load();
        return parent::addIdEcrivain($idEcrivain);
    }

    public function removeIdEcrivain(\ifrikiya\SiteBundle\Entity\Ecrivains $idEcrivain)
    {
        $this->__load();
        return parent::removeIdEcrivain($idEcrivain);
    }

    public function getIdEcrivain()
    {
        $this->__load();
        return parent::getIdEcrivain();
    }

    public function setIdCollection(\ifrikiya\SiteBundle\Entity\Collections $idCollection = NULL)
    {
        $this->__load();
        return parent::setIdCollection($idCollection);
    }

    public function getIdCollection()
    {
        $this->__load();
        return parent::getIdCollection();
    }

    public function setIdGenre(\ifrikiya\SiteBundle\Entity\Genres $idGenre = NULL)
    {
        $this->__load();
        return parent::setIdGenre($idGenre);
    }

    public function getIdGenre()
    {
        $this->__load();
        return parent::getIdGenre();
    }

    public function findByStringTitre($titre)
    {
        $this->__load();
        return parent::findByStringTitre($titre);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idlivre', 'titre', 'annee', 'presentation', 'prixUnitaireFcfa', 'format', 'prixUnitaireEuro', 'idEcrivain', 'idCollection', 'idGenre');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}